const state={name:'Untitled project',messages:[],screen:null};
const $=id=>document.getElementById(id);
const toast=(text)=>{const el=$('toast');el.textContent=text;el.classList.add('show');setTimeout(()=>el.classList.remove('show'),2200)};
function setProjectName(name){state.name=name||'Untitled project';$('projectName').textContent=state.name;$('projectLabel').textContent=state.name;document.title=`${state.name} — Switchbuilder`}
function addMessage(text,type='assistant'){const wrap=$('messages'),row=document.createElement('div');row.className=`message ${type}`;row.innerHTML=`<div class="avatar">${type==='user'?'You':'S'}</div><div class="bubble">${text}</div>`;wrap.appendChild(row);wrap.scrollTop=wrap.scrollHeight;state.messages.push({text,type})}
function makeScreen(prompt){const lower=prompt.toLowerCase();let title='My new app',heading='Welcome to your app',description='A simple starting point generated from your idea.';if(lower.includes('habit')){title='Daily habits';heading='Keep your streak going';description='Track the small actions that move you forward.'}else if(lower.includes('budget')||lower.includes('finance')){title='Money planner';heading='Your month at a glance';description='See where your money is going and stay in control.'}else if(lower.includes('recipe')||lower.includes('food')){title='Recipe box';heading='What are you cooking?';description='Save favorites and keep your shopping list close.'}else{const words=prompt.replace(/[^a-zA-Z0-9 ]/g,'').split(' ').filter(Boolean);title=words.slice(0,3).join(' ')||title;heading=`Welcome to ${title}`}
return {title,heading,description}}
function renderPreview(screen){state.screen=screen;$('previewTitle').textContent=screen.title;const content=$('previewContent');content.innerHTML=`<div class="generated-card"><h4>${screen.heading}</h4><p>${screen.description}</p><div class="fake-row"></div><div class="fake-row" style="width:72%"></div><div class="fake-button"></div></div><div class="generated-card"><h4>Next steps</h4><p>Ask Switchbuilder to change this screen or add features.</p></div>`}
function handlePrompt(text){if(!text.trim())return;addMessage(text.trim(),'user');$('promptInput').value='';setTimeout(()=>{const screen=makeScreen(text);renderPreview(screen);if(state.name==='Untitled project')setProjectName(screen.title);addMessage(`I created a first version of <strong>${screen.title}</strong> in the preview. You can ask me to add screens, change the style, or add functionality.`, 'assistant')},450)}
$('promptForm').addEventListener('submit',e=>{e.preventDefault();handlePrompt($('promptInput').value)});$('promptInput').addEventListener('keydown',e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();$('promptForm').requestSubmit()}});document.querySelectorAll('[data-prompt]').forEach(b=>b.addEventListener('click',()=>handlePrompt(b.dataset.prompt)));
$('saveButton').addEventListener('click',()=>{localStorage.setItem('switchbuilder-project',JSON.stringify(state));$('saveStatus').textContent='Saved just now';toast('Project saved on this device')});$('renameButton').addEventListener('click',()=>{const name=prompt('Project name',state.name);if(name!==null&&name.trim())setProjectName(name.trim())});$('newProjectButton').addEventListener('click',()=>{if(!confirm('Start a new project?'))return;localStorage.removeItem('switchbuilder-project');location.reload()});$('refreshButton').addEventListener('click',()=>{if(state.screen)renderPreview(state.screen);toast('Preview refreshed')});
function exportProject(){const blob=new Blob([JSON.stringify({project:'Switchbuilder',...state},null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`${state.name.replace(/\s+/g,'-').toLowerCase()}-switchbuilder.json`;a.click();URL.revokeObjectURL(a.href);toast('Project export downloaded')}
$('exportBarButton').addEventListener('click',exportProject);$('exportButton').addEventListener('click',()=>{if(!state.screen){toast('Describe your app first');return}toast('Android build queued — export integration is next')});$('fullscreenButton').addEventListener('click',()=>{$('phone').classList.toggle('expanded');toast('Preview focus toggled')});
const saved=localStorage.getItem('switchbuilder-project');if(saved){try{const old=JSON.parse(saved);Object.assign(state,old);setProjectName(state.name);state.messages.forEach(m=>addMessage(m.text,m.type));if(state.screen)renderPreview(state.screen);$('saveStatus').textContent='Saved locally'}catch(e){localStorage.removeItem('switchbuilder-project')}}
