const $=id=>document.getElementById(id);const state={id:null,name:'Untitled project',messages:[],schema:null,dirty:false};
const toast=text=>{const e=$('toast');e.textContent=text;e.classList.add('show');setTimeout(()=>e.classList.remove('show'),2400)};const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function setName(name){state.name=name||'Untitled project';$('projectName').textContent=state.name;$('projectLabel').textContent=state.name;document.title=`${state.name} — Switchbuilder`}
function addMessage(text,type='assistant',save=true){const row=document.createElement('div');row.className=`message ${type}`;row.innerHTML=`<div class="avatar">${type==='user'?'You':'S'}</div><div class="bubble">${text}</div>`;$('messages').appendChild(row);$('messages').scrollTop=$('messages').scrollHeight;if(save)state.messages.push({text,type})}
function elementHtml(el){if(el.type==='text')return `<p class="schema-text">${esc(el.text)}</p>`;if(el.type==='button')return `<button class="schema-button">${esc(el.label||'Continue')}</button>`;if(el.type==='input')return `<label class="schema-label">${esc(el.label||'Input')}<input placeholder="${esc(el.placeholder||'')}" /></label>`;if(el.type==='list')return `<div class="schema-list">${(el.items||[]).map(x=>`<div>✓ <span>${esc(x)}</span></div>`).join('')}</div>`;if(el.type==='card')return `<div class="schema-card"><strong>${esc(el.title||'Card')}</strong><p>${esc(el.text||'')}</p></div>`;if(el.type==='form')return `<div class="schema-form">${(el.fields||[]).map(x=>elementHtml({type:'input',...x})).join('')}<button class="schema-button">${esc(el.submitLabel||'Save')}</button></div>`;return '<div class="schema-spacer"></div>'}
function renderPreview(schema){if(!schema)return;state.schema=schema;$('previewTitle').textContent=schema.app.name;const screen=schema.screens[0]||{title:'Home',elements:[]};$('previewContent').innerHTML=`<h4 class="screen-title">${esc(screen.title)}</h4>${screen.subtitle?`<p class="screen-subtitle">${esc(screen.subtitle)}</p>`:''}${(screen.elements||[]).map(elementHtml).join('')}`;$('phoneNav').innerHTML=(schema.navigation||[]).slice(0,4).map((n,i)=>`<span class="${i?'':'active'}">${n.icon==='settings'?'⚙':'⌂'}<small>${esc(n.label)}</small></span>`).join('')}
async function api(url,options={}){const r=await fetch(url,{headers:{'content-type':'application/json',...(options.headers||{})},...options});const data=await r.json();if(!r.ok)throw new Error(data.error||`Request failed (${r.status})`);return data}
async function generate(prompt){$('connectionStatus').textContent='Thinking…';try{const result=await api('/api/generate',{method:'POST',body:JSON.stringify({prompt,schema:state.schema})});renderPreview(result.schema);if(state.name==='Untitled project')setName(result.schema.app.name);addMessage(`I updated <strong>${esc(result.schema.app.name)}</strong> using the ${result.provider==='ai'?'AI backend':'local generator'}. Ask for another screen, a style change, or a new feature.`);state.dirty=true;$('connectionStatus').textContent=result.provider==='ai'?'AI connected':'Local AI';}catch(e){addMessage(`<strong>Could not generate that yet.</strong> ${esc(e.message)}`);$('connectionStatus').textContent='AI unavailable';toast(e.message)} }
function handlePrompt(text){text=text.trim();if(!text)return;addMessage(esc(text),'user');$('promptInput').value='';generate(text)}
async function save(){try{const body={name:state.name,schema:state.schema,messages:state.messages};const data=state.id?await api(`/api/projects/${state.id}`,{method:'PUT',body:JSON.stringify(body)}):await api('/api/projects',{method:'POST',body:JSON.stringify(body)});state.id=data.id;state.dirty=false;$('saveStatus').textContent='Saved just now';$('projectStorage').textContent='Saved to Switchbuilder';await loadProjects();toast('Project saved')}catch(e){localStorage.setItem('switchbuilder-draft',JSON.stringify(state));$('saveStatus').textContent='Saved locally';toast(`Server unavailable — saved on this device`)}}
async function loadProjects(){try{const {projects}=await api('/api/projects');$('projectSelect').innerHTML='<option value="">Open project…</option>'+projects.map(p=>`<option value="${p.id}">${esc(p.name)}</option>`).join('')}catch(e){}}
async function openProject(id){if(!id)return;try{const p=await api(`/api/projects/${id}`);Object.assign(state,p);setName(state.name);$('messages').innerHTML='';state.messages.forEach(m=>addMessage(m.text,m.type,false));if(state.schema)renderPreview(state.schema);$('projectStorage').textContent='Saved to Switchbuilder';$('saveStatus').textContent='Saved';toast('Project opened')}catch(e){toast(e.message)}}
function exportProject(){const blob=new Blob([JSON.stringify({project:'Switchbuilder',...state},null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`${state.name.replace(/\s+/g,'-').toLowerCase()}-switchbuilder.json`;a.click();URL.revokeObjectURL(a.href)}
$('promptForm').addEventListener('submit',e=>{e.preventDefault();handlePrompt($('promptInput').value)});$('promptInput').addEventListener('keydown',e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();$('promptForm').requestSubmit()}});document.querySelectorAll('[data-prompt]').forEach(b=>b.onclick=()=>handlePrompt(b.dataset.prompt));$('saveButton').onclick=save;$('projectSelect').onchange=e=>openProject(e.target.value);$('exportBarButton').onclick=exportProject;$('renameButton').onclick=()=>{const n=prompt('Project name',state.name);if(n?.trim()){setName(n.trim());state.dirty=true}};$('newProjectButton').onclick=()=>{if(confirm('Start a new project?'))location.reload()};$('refreshButton').onclick=()=>state.schema&&renderPreview(state.schema);$('fullscreenButton').onclick=()=>{$('phone').classList.toggle('expanded')};$('exportButton').onclick=async()=>{if(!state.schema)return toast('Describe your app first');try{await api('/api/build',{method:'POST',body:JSON.stringify({projectId:state.id,schema:state.schema})})}catch(e){toast(e.message)}};
(async()=>{await loadProjects();const draft=localStorage.getItem('switchbuilder-draft');if(draft)try{Object.assign(state,JSON.parse(draft));setName(state.name);if(state.schema)renderPreview(state.schema)}catch(e){}})();
