const fs=require('fs');const path=require('path');const crypto=require('crypto');const {spawn,execFileSync}=require('child_process');
const root=__dirname,buildRoot=path.join(root,'data','builds');fs.mkdirSync(buildRoot,{recursive:true});
const timeoutMs=Number(process.env.BUILD_TIMEOUT_MS||600000);const gradle=process.env.GRADLE_COMMAND||'gradle';
const allowed=new Set(['text','button','input','list','card','form','spacer']);
function valid(s){if(!s||s.version!==1||!s.app||typeof s.app.name!=='string'||s.app.name.length>80||!s.theme||!/^#[\da-f]{6}$/i.test(s.theme.primary)||!/^#[\da-f]{6}$/i.test(s.theme.background)||!/^#[\da-f]{6}$/i.test(s.theme.text)||!Array.isArray(s.screens)||!s.screens.length||s.screens.length>20||!Array.isArray(s.navigation)||s.navigation.length>6)return{valid:false,error:'Invalid app schema'};const ids=new Set(s.screens.map(x=>x.id));for(const n of s.navigation)if(!ids.has(n.screenId))return{valid:false,error:'Navigation references an unknown screen'};for(const x of s.screens){if(typeof x.id!=='string'||typeof x.title!=='string'||!Array.isArray(x.elements))return{valid:false,error:'Invalid screen'};for(const e of x.elements){if(!allowed.has(e.type))return{valid:false,error:`Unsupported element: ${e.type}`};if(e.type==='text'&&typeof e.text!=='string')return{valid:false,error:'Invalid text'};if(e.type==='list'&&(!Array.isArray(e.items)||e.items.length>50))return{valid:false,error:'Invalid list'}}}return{valid:true}}
function escJava(v){return String(v||'').replace(/\\/g,'\\\\').replace(/"/g,'\\"').replace(/[\r\n]/g,' ')}
function writeProject(s,dir){const a=escJava(s.app.name),sc=s.screens[0],color=s.theme.primary;const actions=(sc.elements||[]).map(e=>e.type==='text'?`text(root,"${escJava(e.text)}");`:e.type==='button'?`button(root,"${escJava(e.label)}");`:e.type==='input'?`input(root,"${escJava(e.label)}","${escJava(e.placeholder)}");`:e.type==='list'?`list(root,new String[]{${e.items.map(i=>`"${escJava(i)}"`).join(',')}});`:e.type==='card'?`text(root,"${escJava(e.title||'Card')}");text(root,"${escJava(e.text)}");`: '').join('');const files={
'settings.gradle':"pluginManagement { repositories { google(); mavenCentral(); gradlePluginPortal() } }\ndependencyResolutionManagement { repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS); repositories { google(); mavenCentral() } }\nrootProject.name='SwitchbuilderGenerated'\ninclude ':app'\n",
'build.gradle':"plugins { id 'com.android.application' version '8.5.2' apply false }\n",
'gradle.properties':'org.gradle.jvmargs=-Xmx1536m\nandroid.useAndroidX=true\n',
'app/build.gradle':"plugins { id 'com.android.application' }\nandroid { namespace 'com.switchbuilder.generated'; compileSdk 35\n defaultConfig { applicationId 'com.switchbuilder.generated'; minSdk 23; targetSdk 35; versionCode 1; versionName '1.0' } }\n",
'app/src/main/AndroidManifest.xml':`<manifest xmlns:android="http://schemas.android.com/apk/res/android"><application android:theme="@style/AppTheme" android:label="${a}"><activity android:name=".MainActivity" android:exported="true"><intent-filter><action android:name="android.intent.action.MAIN"/><category android:name="android.intent.category.LAUNCHER"/></intent-filter></activity></application></manifest>`,
'app/src/main/res/values/styles.xml':`<resources><style name="AppTheme" parent="android:style/Theme.Material.Light.NoActionBar"><item name="android:colorAccent">${color}</item></style></resources>`,
'app/src/main/java/com/switchbuilder/generated/MainActivity.java':`package com.switchbuilder.generated;import android.app.*;import android.os.*;import android.graphics.Color;import android.view.*;import android.widget.*;public class MainActivity extends Activity{LinearLayout root;public void onCreate(Bundle b){super.onCreate(b);root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setPadding(32,40,32,24);root.setBackgroundColor(Color.parseColor("${s.theme.background}"));text(root,"${escJava(sc.title)}");${actions}setContentView(root);}void text(ViewGroup r,String x){TextView v=new TextView(this);v.setText(x);v.setTextSize(16);v.setPadding(0,14,0,8);r.addView(v);}void button(ViewGroup r,String x){Button b=new Button(this);b.setText(x);r.addView(b);}void input(ViewGroup r,String l,String h){EditText e=new EditText(this);e.setHint(h);e.setContentDescription(l);r.addView(e);}void list(ViewGroup r,String[] x){for(String i:x)text(r,"• "+i);}}`};for(const [f,c] of Object.entries(files)){const p=path.join(dir,f);fs.mkdirSync(path.dirname(p),{recursive:true});fs.writeFileSync(p,c)}}
function capability(){const out={gradle:false,java:false,androidSdk:Boolean(process.env.ANDROID_SDK_ROOT||process.env.ANDROID_HOME),command:gradle};try{execFileSync('java',['-version'],{stdio:'ignore'});out.java=true}catch{}try{execFileSync(gradle,['--version'],{stdio:'ignore'});out.gradle=true}catch{}return out}
function startBuild(schema,id,onUpdate){const dir=path.join(buildRoot,id,'project'),out=path.join(dir,'app','build','outputs','apk','release','app-release.apk');fs.mkdirSync(dir,{recursive:true});onUpdate({status:'generating',message:'Generating isolated Android project'});writeProject(schema,dir);const cap=capability();if(!cap.gradle||!cap.java||!cap.androidSdk){onUpdate({status:'failed',message:'Android build prerequisites unavailable: Java, Gradle, or ANDROID_SDK_ROOT is missing.',error:JSON.stringify(cap)});return}onUpdate({status:'building',message:'Running Gradle assembleRelease'});let logs='';const child=spawn(gradle,['--no-daemon','--stacktrace','assembleRelease'],{cwd:dir,shell:false,env:{...process.env,CI:'true'}});const timer=setTimeout(()=>{child.kill('SIGKILL');onUpdate({status:'failed',message:`Build timed out after ${timeoutMs/1000}s`,logs:logs.slice(-16000)})},timeoutMs);for(const stream of [child.stdout,child.stderr])stream.on('data',d=>{logs+=d.toString();onUpdate({logs:logs.slice(-16000),message:'Gradle is compiling the Android project'})});child.on('error',e=>{clearTimeout(timer);onUpdate({status:'failed',message:`Could not start Gradle: ${e.message}`,logs})});child.on('close',code=>{clearTimeout(timer);if(code===0&&fs.existsSync(out)&&fs.statSync(out).size>0){const artifact=path.join(buildRoot,id,'app-release.apk');fs.copyFileSync(out,artifact);onUpdate({status:'success',message:'APK verified and ready',artifact:`/api/builds/${id}/download`,logs:logs.slice(-16000)})}else onUpdate({status:'failed',message:`Gradle failed with exit code ${code}`,logs:logs.slice(-16000)})})}
module.exports={valid,startBuild,capability};
