const fs=require('fs');const path=require('path');const http=require('http');const {URL}=require('url');
const root=__dirname, dataDir=path.join(root,'data','projects');fs.mkdirSync(dataDir,{recursive:true});
const PORT=Number(process.env.PORT||8787);const AI_URL=process.env.AI_API_URL||'https://api.openai.com/v1/chat/completions';
const schemaExample={version:1,app:{name:'Habit tracker',description:'Track daily habits'},theme:{primary:'#6d5dfc',background:'#ffffff',text:'#17152a'},navigation:[{label:'Home',screenId:'home',icon:'home'},{label:'Settings',screenId:'settings',icon:'settings'}],screens:[{id:'home',title:'Today',subtitle:'Small steps every day.',elements:[{type:'text',text:'Your habits'},{type:'list',items:['Drink water','Walk for 20 minutes']},{type:'button',label:'Add habit',action:'add-habit'}]}]};
const system=`You are Switchbuilder's app architect. Return ONLY valid JSON matching this schema: ${JSON.stringify(schemaExample)}. Use screen elements of type text, button, input, list, card, spacer, form. Buttons need label and action; inputs need label and placeholder; forms may contain fields. Preserve a useful existing app structure when the user asks for a change. Keep it mobile-friendly and do not include markdown.`;
function send(res,status,payload){res.writeHead(status,{'content-type':'application/json','access-control-allow-origin':'*'});res.end(JSON.stringify(payload))}function body(req){return new Promise((resolve,reject)=>{let b='';req.on('data',c=>b+=c);req.on('end',()=>{try{resolve(b?JSON.parse(b):{})}catch(e){reject(e)}})})}
function valid(s){return s&&s.version===1&&s.app&&Array.isArray(s.screens)&&s.theme&&Array.isArray(s.navigation)}
function localGenerate(prompt,current){const p=prompt.toLowerCase();let name=current?.app?.name||'My new app',title='Home',subtitle='A simple starting point for your idea.',items=['Get started','Your first item'];if(p.includes('habit')){name='Daily habits';title='Today';subtitle='Keep your streak going.';items=['Drink water','Move for 20 minutes','Read for 10 minutes']}else if(p.includes('budget')||p.includes('finance')){name='Money planner';title='Overview';subtitle='Your month at a glance.';items=['Income $2,400','Expenses $1,120','Remaining $1,280']}else if(p.includes('recipe')||p.includes('food')){name='Recipe box';title='Recipes';subtitle='What are you cooking today?';items=['Favorites','Quick dinners','Shopping list']}else{name=(prompt.match(/(?:called|named) ([\w -]+)/i)||[])[1]?.trim()||name}return {version:1,app:{name,description:prompt},theme:{primary:'#6d5dfc',background:'#ffffff',text:'#17152a'},navigation:[{label:'Home',screenId:'home',icon:'home'},{label:'Settings',screenId:'settings',icon:'settings'}],screens:[{id:'home',title,subtitle,elements:[{type:'text',text:subtitle},{type:'list',items},{type:'button',label:'Add item',action:'add-item'}]},{id:'settings',title:'Settings',elements:[{type:'text',text:'Customize your experience.'},{type:'input',label:'Your name',placeholder:'Enter your name'}]}]}}
async function generate(prompt,current){if(!process.env.AI_API_KEY)return {schema:localGenerate(prompt,current),provider:'local'};const r=await fetch(AI_URL,{method:'POST',headers:{'content-type':'application/json',authorization:`Bearer ${process.env.AI_API_KEY}`},body:JSON.stringify({model:process.env.AI_MODEL||'gpt-4o-mini',temperature:.2,response_format:{type:'json_object'},messages:[{role:'system',content:system},{role:'user',content:JSON.stringify({request:prompt,current})}]})});if(!r.ok)throw new Error(`AI provider returned ${r.status}`);const j=await r.json(),text=j.choices?.[0]?.message?.content||'';const schema=JSON.parse(text);if(!valid(schema))throw new Error('AI returned an invalid app schema');return {schema,provider:'ai'}}
function projectPath(id){return path.join(dataDir,`${id}.json`)}function id(){return `project-${Date.now()}-${Math.random().toString(36).slice(2,7)}`}
async function route(req,res){const u=new URL(req.url,`http://${req.headers.host}`);if(req.method==='OPTIONS')return send(res,204,{});try{if(req.method==='GET'&&u.pathname==='/api/projects'){const list=fs.readdirSync(dataDir).filter(x=>x.endsWith('.json')).map(x=>JSON.parse(fs.readFileSync(path.join(dataDir,x)))).sort((a,b)=>b.updatedAt.localeCompare(a.updatedAt));return send(res,200,{projects:list.map(({id,name,updatedAt})=>({id,name,updatedAt}))})}if(req.method==='GET'&&u.pathname.startsWith('/api/projects/')){const p=JSON.parse(fs.readFileSync(projectPath(u.pathname.split('/').pop())));return send(res,200,p)}if(req.method==='POST'&&u.pathname==='/api/projects'){const b=await body(req),p={id:id(),name:b.name||'Untitled project',schema:b.schema||null,messages:b.messages||[],createdAt:new Date().toISOString(),updatedAt:new Date().toISOString()};fs.writeFileSync(projectPath(p.id),JSON.stringify(p,null,2));return send(res,201,p)}if(req.method==='PUT'&&u.pathname.startsWith('/api/projects/')){const file=projectPath(u.pathname.split('/').pop()),old=JSON.parse(fs.readFileSync(file)),b=await body(req),p={...old,...b,updatedAt:new Date().toISOString()};fs.writeFileSync(file,JSON.stringify(p,null,2));return send(res,200,p)}if(req.method==='POST'&&u.pathname==='/api/generate'){const b=await body(req);return send(res,200,await generate(b.prompt,b.schema))}if(req.method==='POST'&&u.pathname==='/api/build'){if(!process.env.BUILD_WORKER_URL)return send(res,501,{error:'No Android build worker is configured. Set BUILD_WORKER_URL when a real worker is available.'});return send(res,501,{error:'Build worker adapter is reserved and not yet implemented.'})}if(req.method==='GET'){let file=u.pathname==='/'?'index.html':u.pathname.slice(1),full=path.join(root,file);if(!full.startsWith(root)||!fs.existsSync(full))return send(res,404,{error:'Not found'});const ext=path.extname(full),types={'.html':'text/html','.js':'text/javascript','.css':'text/css','.json':'application/json'};res.writeHead(200,{'content-type':types[ext]||'text/plain'});return fs.createReadStream(full).pipe(res)}send(res,404,{error:'Not found'})}catch(e){console.error(e);send(res,e.code==='ENOENT'?404:500,{error:e.message})}}
http.createServer(route).listen(PORT,()=>console.log(`Switchbuilder running at http://localhost:${PORT}`));
